apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/component: go-service
    app.kubernetes.io/part-of: nomarkup
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: notification
  ports:
    - name: grpc
      port: 50059
      targetPort: grpc
      protocol: TCP
