#!/usr/bin/env bash
# Writes ios/NoMarkup/Core/GitRevision.swift with the current short SHA.
# Run from repo root or via Xcode (SRCROOT = ios/).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
IOS_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$IOS_ROOT/.." && pwd)"
OUT="$IOS_ROOT/NoMarkup/Core/GitRevision.swift"

cd "$REPO_ROOT"
SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
    SHA="${SHA}-dirty"
  fi
fi
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"

cat >"$OUT" <<EOF
// Auto-generated by ios/scripts/stamp-git-revision.sh — do not edit by hand.
// Regenerated on each device/sim build so Home footer shows the real revision.

enum GitRevision {
    /// Short git SHA (appends \`-dirty\` when the working tree has uncommitted changes).
    static let short: String = "${SHA}"
    /// Branch name at stamp time.
    static let branch: String = "${BRANCH}"
}
EOF

echo "stamped GitRevision short=${SHA} branch=${BRANCH} → ${OUT}"
