#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
IOS_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$IOS_ROOT/.." && pwd)"
OUT="$IOS_ROOT/NoMarkup/Core/GitRevision.swift"
cd "$REPO_ROOT"
SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
DIRTY=""
# Only tracked changes count as dirty (untracked agent/docs noise ignored).
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  if ! git diff --quiet -- . ':(exclude)ios/NoMarkup/Core/GitRevision.swift' 2>/dev/null \
     || ! git diff --cached --quiet -- . ':(exclude)ios/NoMarkup/Core/GitRevision.swift' 2>/dev/null; then
    DIRTY="-dirty"
  fi
fi
SHA="${SHA}${DIRTY}"
cat >"$OUT" <<EOF
// Auto-generated by ios/scripts/stamp-git-revision.sh — do not edit by hand.
// Regenerated on each device/sim build so Home footer shows the real revision.

enum GitRevision {
    /// Short git SHA (appends \`-dirty\` when tracked sources differ from HEAD).
    static let short: String = "${SHA}"
    /// Branch name at stamp time.
    static let branch: String = "${BRANCH}"
}
EOF
echo "stamped GitRevision short=${SHA} branch=${BRANCH}"

# Stamp DEBUG device LAN API base (en0/en1).
LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
DEV_OUT="$IOS_ROOT/NoMarkup/Core/DevAPIBase.swift"
if [ -n "${LAN_IP}" ]; then
  LAN_URL="http://${LAN_IP}:8081"
else
  LAN_URL=""
fi
cat >"$DEV_OUT" <<EOF
// Auto-generated by ios/scripts/stamp-git-revision.sh — do not edit by hand.
// DEBUG physical-device default gateway (LAN). Empty string disables device default.

enum DevAPIBase {
    /// e.g. \`http://192.168.1.101:8081\` — used only in DEBUG non-simulator builds.
    static let lanURLString: String = "${LAN_URL}"
}
EOF
echo "stamped DevAPIBase lanURLString=${LAN_URL}"

