// Auto-generated by ios/scripts/stamp-git-revision.sh — do not edit by hand.
// DEBUG physical-device default gateway (LAN). Empty string disables device default.

enum DevAPIBase {
    /// e.g. `http://192.168.1.101:8081` — used only in DEBUG non-simulator builds.
    static let lanURLString: String = "http://192.168.1.101:8081"
}
