// Auto-generated by ios/scripts/stamp-git-revision.sh — do not edit by hand.
// Regenerated on each device/sim build so Home footer shows the real revision.

enum GitRevision {
    /// Short git SHA (appends `-dirty` when tracked sources differ from HEAD).
    static let short: String = "d4f904d8"
    /// Branch name at stamp time.
    static let branch: String = "fix/security-audit-2026-04-23"
}
