-- Market catalog: every city/region NoMarkup can operate in, modeled on
-- craigslist's one-site-per-metro coverage (source: craigslist.org/about/sites,
-- crawled 2026-06-07). One row per market; `slug` is the craigslist subdomain
-- (globally unique), reused as our market key.
--
-- Markets seed with is_active=false: this is the *catalog* of where we COULD
-- launch, not where we're live. Ops flips is_active=true per market as it opens.
-- lat/lng/location are nullable here (the directory has no coordinates); a
-- follow-up geocoding backfill populates them. Down migration drops the table.

CREATE TABLE markets (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        TEXT NOT NULL UNIQUE,            -- craigslist subdomain, e.g. 'sfbay'
  name        TEXT NOT NULL,                   -- display name, e.g. 'SF bay area'
  region      TEXT,                            -- US state / 'Territories'; NULL for MX
  region_code TEXT,                            -- 2-letter US state code; NULL otherwise
  country     TEXT NOT NULL CHECK (country IN ('US','MX')),
  source      TEXT NOT NULL DEFAULT 'craigslist',
  is_active   BOOLEAN NOT NULL DEFAULT false,  -- launched in this market yet?
  lat         DOUBLE PRECISION,                -- nullable until geocode backfill
  lng         DOUBLE PRECISION,
  location    GEOGRAPHY(Point, 4326),          -- nullable; GIST index below
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_markets_country_region ON markets (country, region);
CREATE INDEX idx_markets_active ON markets (is_active) WHERE is_active = true;
CREATE INDEX idx_markets_location ON markets USING GIST (location);

CREATE TRIGGER set_updated_at_markets
  BEFORE UPDATE ON markets
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

INSERT INTO markets (slug, name, region, region_code, country) VALUES
  ('auburn', 'auburn', 'Alabama', 'AL', 'US'),
  ('bham', 'birmingham', 'Alabama', 'AL', 'US'),
  ('dothan', 'dothan', 'Alabama', 'AL', 'US'),
  ('shoals', 'florence / muscle shoals', 'Alabama', 'AL', 'US'),
  ('gadsden', 'gadsden-anniston', 'Alabama', 'AL', 'US'),
  ('huntsville', 'huntsville / decatur', 'Alabama', 'AL', 'US'),
  ('mobile', 'mobile', 'Alabama', 'AL', 'US'),
  ('montgomery', 'montgomery', 'Alabama', 'AL', 'US'),
  ('tuscaloosa', 'tuscaloosa', 'Alabama', 'AL', 'US'),
  ('anchorage', 'anchorage / mat-su', 'Alaska', 'AK', 'US'),
  ('fairbanks', 'fairbanks', 'Alaska', 'AK', 'US'),
  ('kenai', 'kenai peninsula', 'Alaska', 'AK', 'US'),
  ('juneau', 'southeast alaska', 'Alaska', 'AK', 'US'),
  ('flagstaff', 'flagstaff / sedona', 'Arizona', 'AZ', 'US'),
  ('mohave', 'mohave county', 'Arizona', 'AZ', 'US'),
  ('phoenix', 'phoenix', 'Arizona', 'AZ', 'US'),
  ('prescott', 'prescott', 'Arizona', 'AZ', 'US'),
  ('showlow', 'show low', 'Arizona', 'AZ', 'US'),
  ('sierravista', 'sierra vista', 'Arizona', 'AZ', 'US'),
  ('tucson', 'tucson', 'Arizona', 'AZ', 'US'),
  ('yuma', 'yuma', 'Arizona', 'AZ', 'US'),
  ('fayar', 'fayetteville', 'Arkansas', 'AR', 'US'),
  ('fortsmith', 'fort smith', 'Arkansas', 'AR', 'US'),
  ('jonesboro', 'jonesboro', 'Arkansas', 'AR', 'US'),
  ('littlerock', 'little rock', 'Arkansas', 'AR', 'US'),
  ('texarkana', 'texarkana', 'Arkansas', 'AR', 'US'),
  ('bakersfield', 'bakersfield', 'California', 'CA', 'US'),
  ('chico', 'chico', 'California', 'CA', 'US'),
  ('fresno', 'fresno / madera', 'California', 'CA', 'US'),
  ('goldcountry', 'gold country', 'California', 'CA', 'US'),
  ('hanford', 'hanford-corcoran', 'California', 'CA', 'US'),
  ('humboldt', 'humboldt county', 'California', 'CA', 'US'),
  ('imperial', 'imperial county', 'California', 'CA', 'US'),
  ('inlandempire', 'inland empire', 'California', 'CA', 'US'),
  ('losangeles', 'los angeles', 'California', 'CA', 'US'),
  ('mendocino', 'mendocino county', 'California', 'CA', 'US'),
  ('merced', 'merced', 'California', 'CA', 'US'),
  ('modesto', 'modesto', 'California', 'CA', 'US'),
  ('monterey', 'monterey bay', 'California', 'CA', 'US'),
  ('orangecounty', 'orange county', 'California', 'CA', 'US'),
  ('palmsprings', 'palm springs', 'California', 'CA', 'US'),
  ('redding', 'redding', 'California', 'CA', 'US'),
  ('sacramento', 'sacramento', 'California', 'CA', 'US'),
  ('sandiego', 'san diego', 'California', 'CA', 'US'),
  ('sfbay', 'san francisco bay area', 'California', 'CA', 'US'),
  ('slo', 'san luis obispo', 'California', 'CA', 'US'),
  ('santabarbara', 'santa barbara', 'California', 'CA', 'US'),
  ('santamaria', 'santa maria', 'California', 'CA', 'US'),
  ('siskiyou', 'siskiyou county', 'California', 'CA', 'US'),
  ('stockton', 'stockton', 'California', 'CA', 'US'),
  ('susanville', 'susanville', 'California', 'CA', 'US'),
  ('ventura', 'ventura county', 'California', 'CA', 'US'),
  ('visalia', 'visalia-tulare', 'California', 'CA', 'US'),
  ('yubasutter', 'yuba-sutter', 'California', 'CA', 'US'),
  ('boulder', 'boulder', 'Colorado', 'CO', 'US'),
  ('cosprings', 'colorado springs', 'Colorado', 'CO', 'US'),
  ('denver', 'denver', 'Colorado', 'CO', 'US'),
  ('eastco', 'eastern CO', 'Colorado', 'CO', 'US'),
  ('fortcollins', 'fort collins / north CO', 'Colorado', 'CO', 'US'),
  ('rockies', 'high rockies', 'Colorado', 'CO', 'US'),
  ('pueblo', 'pueblo', 'Colorado', 'CO', 'US'),
  ('westslope', 'western slope', 'Colorado', 'CO', 'US'),
  ('newlondon', 'eastern CT', 'Connecticut', 'CT', 'US'),
  ('hartford', 'hartford', 'Connecticut', 'CT', 'US'),
  ('newhaven', 'new haven', 'Connecticut', 'CT', 'US'),
  ('nwct', 'northwest CT', 'Connecticut', 'CT', 'US'),
  ('delaware', 'delaware', 'Delaware', 'DE', 'US'),
  ('washingtondc', 'washington', 'District of Columbia', 'DC', 'US'),
  ('miami', 'broward county', 'Florida', 'FL', 'US'),
  ('daytona', 'daytona beach', 'Florida', 'FL', 'US'),
  ('keys', 'florida keys', 'Florida', 'FL', 'US'),
  ('fortmyers', 'ft myers / SW florida', 'Florida', 'FL', 'US'),
  ('gainesville', 'gainesville', 'Florida', 'FL', 'US'),
  ('cfl', 'heartland florida', 'Florida', 'FL', 'US'),
  ('jacksonville', 'jacksonville', 'Florida', 'FL', 'US'),
  ('lakeland', 'lakeland', 'Florida', 'FL', 'US'),
  ('lakecity', 'north central FL', 'Florida', 'FL', 'US'),
  ('ocala', 'ocala', 'Florida', 'FL', 'US'),
  ('okaloosa', 'okaloosa / walton', 'Florida', 'FL', 'US'),
  ('orlando', 'orlando', 'Florida', 'FL', 'US'),
  ('panamacity', 'panama city', 'Florida', 'FL', 'US'),
  ('pensacola', 'pensacola', 'Florida', 'FL', 'US'),
  ('sarasota', 'sarasota-bradenton', 'Florida', 'FL', 'US'),
  ('spacecoast', 'space coast', 'Florida', 'FL', 'US'),
  ('staugustine', 'st augustine', 'Florida', 'FL', 'US'),
  ('tallahassee', 'tallahassee', 'Florida', 'FL', 'US'),
  ('tampa', 'tampa bay area', 'Florida', 'FL', 'US'),
  ('treasure', 'treasure coast', 'Florida', 'FL', 'US'),
  ('albanyga', 'albany', 'Georgia', 'GA', 'US'),
  ('athensga', 'athens', 'Georgia', 'GA', 'US'),
  ('atlanta', 'atlanta', 'Georgia', 'GA', 'US'),
  ('augusta', 'augusta', 'Georgia', 'GA', 'US'),
  ('brunswick', 'brunswick', 'Georgia', 'GA', 'US'),
  ('columbusga', 'columbus', 'Georgia', 'GA', 'US'),
  ('macon', 'macon / warner robins', 'Georgia', 'GA', 'US'),
  ('nwga', 'northwest GA', 'Georgia', 'GA', 'US'),
  ('savannah', 'savannah / hinesville', 'Georgia', 'GA', 'US'),
  ('statesboro', 'statesboro', 'Georgia', 'GA', 'US'),
  ('valdosta', 'valdosta', 'Georgia', 'GA', 'US'),
  ('honolulu', 'hawaii', 'Hawaii', 'HI', 'US'),
  ('boise', 'boise', 'Idaho', 'ID', 'US'),
  ('eastidaho', 'east idaho', 'Idaho', 'ID', 'US'),
  ('lewiston', 'lewiston / clarkston', 'Idaho', 'ID', 'US'),
  ('twinfalls', 'twin falls', 'Idaho', 'ID', 'US'),
  ('bn', 'bloomington-normal', 'Illinois', 'IL', 'US'),
  ('chambana', 'champaign urbana', 'Illinois', 'IL', 'US'),
  ('chicago', 'chicago', 'Illinois', 'IL', 'US'),
  ('decatur', 'decatur', 'Illinois', 'IL', 'US'),
  ('lasalle', 'la salle co', 'Illinois', 'IL', 'US'),
  ('mattoon', 'mattoon-charleston', 'Illinois', 'IL', 'US'),
  ('peoria', 'peoria', 'Illinois', 'IL', 'US'),
  ('rockford', 'rockford', 'Illinois', 'IL', 'US'),
  ('carbondale', 'southern illinois', 'Illinois', 'IL', 'US'),
  ('springfieldil', 'springfield', 'Illinois', 'IL', 'US'),
  ('quincy', 'western IL', 'Illinois', 'IL', 'US'),
  ('bloomington', 'bloomington', 'Indiana', 'IN', 'US'),
  ('evansville', 'evansville', 'Indiana', 'IN', 'US'),
  ('fortwayne', 'fort wayne', 'Indiana', 'IN', 'US'),
  ('indianapolis', 'indianapolis', 'Indiana', 'IN', 'US'),
  ('kokomo', 'kokomo', 'Indiana', 'IN', 'US'),
  ('tippecanoe', 'lafayette / west lafayette', 'Indiana', 'IN', 'US'),
  ('muncie', 'muncie / anderson', 'Indiana', 'IN', 'US'),
  ('richmondin', 'richmond', 'Indiana', 'IN', 'US'),
  ('southbend', 'south bend / michiana', 'Indiana', 'IN', 'US'),
  ('terrehaute', 'terre haute', 'Indiana', 'IN', 'US'),
  ('ames', 'ames', 'Iowa', 'IA', 'US'),
  ('cedarrapids', 'cedar rapids', 'Iowa', 'IA', 'US'),
  ('desmoines', 'des moines', 'Iowa', 'IA', 'US'),
  ('dubuque', 'dubuque', 'Iowa', 'IA', 'US'),
  ('fortdodge', 'fort dodge', 'Iowa', 'IA', 'US'),
  ('iowacity', 'iowa city', 'Iowa', 'IA', 'US'),
  ('masoncity', 'mason city', 'Iowa', 'IA', 'US'),
  ('quadcities', 'quad cities', 'Iowa', 'IA', 'US'),
  ('siouxcity', 'sioux city', 'Iowa', 'IA', 'US'),
  ('ottumwa', 'southeast IA', 'Iowa', 'IA', 'US'),
  ('waterloo', 'waterloo / cedar falls', 'Iowa', 'IA', 'US'),
  ('lawrence', 'lawrence', 'Kansas', 'KS', 'US'),
  ('ksu', 'manhattan', 'Kansas', 'KS', 'US'),
  ('nwks', 'northwest KS', 'Kansas', 'KS', 'US'),
  ('salina', 'salina', 'Kansas', 'KS', 'US'),
  ('seks', 'southeast KS', 'Kansas', 'KS', 'US'),
  ('swks', 'southwest KS', 'Kansas', 'KS', 'US'),
  ('topeka', 'topeka', 'Kansas', 'KS', 'US'),
  ('wichita', 'wichita', 'Kansas', 'KS', 'US'),
  ('bgky', 'bowling green', 'Kentucky', 'KY', 'US'),
  ('eastky', 'eastern kentucky', 'Kentucky', 'KY', 'US'),
  ('lexington', 'lexington', 'Kentucky', 'KY', 'US'),
  ('louisville', 'louisville', 'Kentucky', 'KY', 'US'),
  ('owensboro', 'owensboro', 'Kentucky', 'KY', 'US'),
  ('westky', 'western KY', 'Kentucky', 'KY', 'US'),
  ('batonrouge', 'baton rouge', 'Louisiana', 'LA', 'US'),
  ('cenla', 'central louisiana', 'Louisiana', 'LA', 'US'),
  ('houma', 'houma', 'Louisiana', 'LA', 'US'),
  ('lafayette', 'lafayette', 'Louisiana', 'LA', 'US'),
  ('lakecharles', 'lake charles', 'Louisiana', 'LA', 'US'),
  ('monroe', 'monroe', 'Louisiana', 'LA', 'US'),
  ('neworleans', 'new orleans', 'Louisiana', 'LA', 'US'),
  ('shreveport', 'shreveport', 'Louisiana', 'LA', 'US'),
  ('maine', 'maine', 'Maine', 'ME', 'US'),
  ('annapolis', 'annapolis', 'Maryland', 'MD', 'US'),
  ('baltimore', 'baltimore', 'Maryland', 'MD', 'US'),
  ('easternshore', 'eastern shore', 'Maryland', 'MD', 'US'),
  ('frederick', 'frederick', 'Maryland', 'MD', 'US'),
  ('smd', 'southern maryland', 'Maryland', 'MD', 'US'),
  ('westmd', 'western maryland', 'Maryland', 'MD', 'US'),
  ('boston', 'boston', 'Massachusetts', 'MA', 'US'),
  ('capecod', 'cape cod / islands', 'Massachusetts', 'MA', 'US'),
  ('southcoast', 'south coast', 'Massachusetts', 'MA', 'US'),
  ('westernmass', 'western massachusetts', 'Massachusetts', 'MA', 'US'),
  ('worcester', 'worcester / central MA', 'Massachusetts', 'MA', 'US'),
  ('annarbor', 'ann arbor', 'Michigan', 'MI', 'US'),
  ('battlecreek', 'battle creek', 'Michigan', 'MI', 'US'),
  ('centralmich', 'central michigan', 'Michigan', 'MI', 'US'),
  ('detroit', 'detroit metro', 'Michigan', 'MI', 'US'),
  ('flint', 'flint', 'Michigan', 'MI', 'US'),
  ('grandrapids', 'grand rapids', 'Michigan', 'MI', 'US'),
  ('holland', 'holland', 'Michigan', 'MI', 'US'),
  ('jxn', 'jackson', 'Michigan', 'MI', 'US'),
  ('kalamazoo', 'kalamazoo', 'Michigan', 'MI', 'US'),
  ('lansing', 'lansing', 'Michigan', 'MI', 'US'),
  ('monroemi', 'monroe', 'Michigan', 'MI', 'US'),
  ('muskegon', 'muskegon', 'Michigan', 'MI', 'US'),
  ('nmi', 'northern michigan', 'Michigan', 'MI', 'US'),
  ('porthuron', 'port huron', 'Michigan', 'MI', 'US'),
  ('saginaw', 'saginaw-midland-baycity', 'Michigan', 'MI', 'US'),
  ('swmi', 'southwest michigan', 'Michigan', 'MI', 'US'),
  ('thumb', 'the thumb', 'Michigan', 'MI', 'US'),
  ('up', 'upper peninsula', 'Michigan', 'MI', 'US'),
  ('bemidji', 'bemidji', 'Minnesota', 'MN', 'US'),
  ('brainerd', 'brainerd', 'Minnesota', 'MN', 'US'),
  ('duluth', 'duluth / superior', 'Minnesota', 'MN', 'US'),
  ('mankato', 'mankato', 'Minnesota', 'MN', 'US'),
  ('minneapolis', 'minneapolis / st paul', 'Minnesota', 'MN', 'US'),
  ('rmn', 'rochester', 'Minnesota', 'MN', 'US'),
  ('marshall', 'southwest MN', 'Minnesota', 'MN', 'US'),
  ('stcloud', 'st cloud', 'Minnesota', 'MN', 'US'),
  ('gulfport', 'gulfport / biloxi', 'Mississippi', 'MS', 'US'),
  ('hattiesburg', 'hattiesburg', 'Mississippi', 'MS', 'US'),
  ('jackson', 'jackson', 'Mississippi', 'MS', 'US'),
  ('meridian', 'meridian', 'Mississippi', 'MS', 'US'),
  ('northmiss', 'north mississippi', 'Mississippi', 'MS', 'US'),
  ('natchez', 'southwest MS', 'Mississippi', 'MS', 'US'),
  ('columbiamo', 'columbia / jeff city', 'Missouri', 'MO', 'US'),
  ('joplin', 'joplin', 'Missouri', 'MO', 'US'),
  ('kansascity', 'kansas city', 'Missouri', 'MO', 'US'),
  ('kirksville', 'kirksville', 'Missouri', 'MO', 'US'),
  ('loz', 'lake of the ozarks', 'Missouri', 'MO', 'US'),
  ('semo', 'southeast missouri', 'Missouri', 'MO', 'US'),
  ('springfield', 'springfield', 'Missouri', 'MO', 'US'),
  ('stjoseph', 'st joseph', 'Missouri', 'MO', 'US'),
  ('stlouis', 'st louis', 'Missouri', 'MO', 'US'),
  ('billings', 'billings', 'Montana', 'MT', 'US'),
  ('bozeman', 'bozeman', 'Montana', 'MT', 'US'),
  ('butte', 'butte', 'Montana', 'MT', 'US'),
  ('greatfalls', 'great falls', 'Montana', 'MT', 'US'),
  ('helena', 'helena', 'Montana', 'MT', 'US'),
  ('kalispell', 'kalispell', 'Montana', 'MT', 'US'),
  ('missoula', 'missoula', 'Montana', 'MT', 'US'),
  ('montana', 'eastern montana', 'Montana', 'MT', 'US'),
  ('grandisland', 'grand island', 'Nebraska', 'NE', 'US'),
  ('lincoln', 'lincoln', 'Nebraska', 'NE', 'US'),
  ('northplatte', 'north platte', 'Nebraska', 'NE', 'US'),
  ('omaha', 'omaha / council bluffs', 'Nebraska', 'NE', 'US'),
  ('scottsbluff', 'scottsbluff / panhandle', 'Nebraska', 'NE', 'US'),
  ('elko', 'elko', 'Nevada', 'NV', 'US'),
  ('lasvegas', 'las vegas', 'Nevada', 'NV', 'US'),
  ('reno', 'reno / tahoe', 'Nevada', 'NV', 'US'),
  ('nh', 'new hampshire', 'New Hampshire', 'NH', 'US'),
  ('cnj', 'central NJ', 'New Jersey', 'NJ', 'US'),
  ('jerseyshore', 'jersey shore', 'New Jersey', 'NJ', 'US'),
  ('newjersey', 'north jersey', 'New Jersey', 'NJ', 'US'),
  ('southjersey', 'south jersey', 'New Jersey', 'NJ', 'US'),
  ('albuquerque', 'albuquerque', 'New Mexico', 'NM', 'US'),
  ('clovis', 'clovis / portales', 'New Mexico', 'NM', 'US'),
  ('farmington', 'farmington', 'New Mexico', 'NM', 'US'),
  ('lascruces', 'las cruces', 'New Mexico', 'NM', 'US'),
  ('roswell', 'roswell / carlsbad', 'New Mexico', 'NM', 'US'),
  ('santafe', 'santa fe / taos', 'New Mexico', 'NM', 'US'),
  ('albany', 'albany', 'New York', 'NY', 'US'),
  ('binghamton', 'binghamton', 'New York', 'NY', 'US'),
  ('buffalo', 'buffalo', 'New York', 'NY', 'US'),
  ('catskills', 'catskills', 'New York', 'NY', 'US'),
  ('chautauqua', 'chautauqua', 'New York', 'NY', 'US'),
  ('elmira', 'elmira-corning', 'New York', 'NY', 'US'),
  ('fingerlakes', 'finger lakes', 'New York', 'NY', 'US'),
  ('glensfalls', 'glens falls', 'New York', 'NY', 'US'),
  ('hudsonvalley', 'hudson valley', 'New York', 'NY', 'US'),
  ('ithaca', 'ithaca', 'New York', 'NY', 'US'),
  ('longisland', 'long island', 'New York', 'NY', 'US'),
  ('newyork', 'new york city', 'New York', 'NY', 'US'),
  ('oneonta', 'oneonta', 'New York', 'NY', 'US'),
  ('plattsburgh', 'plattsburgh-adirondacks', 'New York', 'NY', 'US'),
  ('potsdam', 'potsdam-canton-massena', 'New York', 'NY', 'US'),
  ('rochester', 'rochester', 'New York', 'NY', 'US'),
  ('syracuse', 'syracuse', 'New York', 'NY', 'US'),
  ('twintiers', 'twin tiers NY/PA', 'New York', 'NY', 'US'),
  ('utica', 'utica-rome-oneida', 'New York', 'NY', 'US'),
  ('watertown', 'watertown', 'New York', 'NY', 'US'),
  ('asheville', 'asheville', 'North Carolina', 'NC', 'US'),
  ('boone', 'boone', 'North Carolina', 'NC', 'US'),
  ('charlotte', 'charlotte', 'North Carolina', 'NC', 'US'),
  ('eastnc', 'eastern NC', 'North Carolina', 'NC', 'US'),
  ('fayetteville', 'fayetteville', 'North Carolina', 'NC', 'US'),
  ('greensboro', 'greensboro', 'North Carolina', 'NC', 'US'),
  ('hickory', 'hickory / lenoir', 'North Carolina', 'NC', 'US'),
  ('onslow', 'jacksonville', 'North Carolina', 'NC', 'US'),
  ('outerbanks', 'outer banks', 'North Carolina', 'NC', 'US'),
  ('raleigh', 'raleigh / durham / CH', 'North Carolina', 'NC', 'US'),
  ('wilmington', 'wilmington', 'North Carolina', 'NC', 'US'),
  ('winstonsalem', 'winston-salem', 'North Carolina', 'NC', 'US'),
  ('bismarck', 'bismarck', 'North Dakota', 'ND', 'US'),
  ('fargo', 'fargo / moorhead', 'North Dakota', 'ND', 'US'),
  ('grandforks', 'grand forks', 'North Dakota', 'ND', 'US'),
  ('nd', 'north dakota', 'North Dakota', 'ND', 'US'),
  ('akroncanton', 'akron / canton', 'Ohio', 'OH', 'US'),
  ('ashtabula', 'ashtabula', 'Ohio', 'OH', 'US'),
  ('athensohio', 'athens', 'Ohio', 'OH', 'US'),
  ('chillicothe', 'chillicothe', 'Ohio', 'OH', 'US'),
  ('cincinnati', 'cincinnati', 'Ohio', 'OH', 'US'),
  ('cleveland', 'cleveland', 'Ohio', 'OH', 'US'),
  ('columbus', 'columbus', 'Ohio', 'OH', 'US'),
  ('dayton', 'dayton / springfield', 'Ohio', 'OH', 'US'),
  ('limaohio', 'lima / findlay', 'Ohio', 'OH', 'US'),
  ('mansfield', 'mansfield', 'Ohio', 'OH', 'US'),
  ('sandusky', 'sandusky', 'Ohio', 'OH', 'US'),
  ('toledo', 'toledo', 'Ohio', 'OH', 'US'),
  ('tuscarawas', 'tuscarawas co', 'Ohio', 'OH', 'US'),
  ('youngstown', 'youngstown', 'Ohio', 'OH', 'US'),
  ('zanesville', 'zanesville / cambridge', 'Ohio', 'OH', 'US'),
  ('lawton', 'lawton', 'Oklahoma', 'OK', 'US'),
  ('enid', 'northwest OK', 'Oklahoma', 'OK', 'US'),
  ('oklahomacity', 'oklahoma city', 'Oklahoma', 'OK', 'US'),
  ('stillwater', 'stillwater', 'Oklahoma', 'OK', 'US'),
  ('tulsa', 'tulsa', 'Oklahoma', 'OK', 'US'),
  ('bend', 'bend', 'Oregon', 'OR', 'US'),
  ('corvallis', 'corvallis/albany', 'Oregon', 'OR', 'US'),
  ('eastoregon', 'east oregon', 'Oregon', 'OR', 'US'),
  ('eugene', 'eugene', 'Oregon', 'OR', 'US'),
  ('klamath', 'klamath falls', 'Oregon', 'OR', 'US'),
  ('medford', 'medford-ashland', 'Oregon', 'OR', 'US'),
  ('oregoncoast', 'oregon coast', 'Oregon', 'OR', 'US'),
  ('portland', 'portland', 'Oregon', 'OR', 'US'),
  ('roseburg', 'roseburg', 'Oregon', 'OR', 'US'),
  ('salem', 'salem', 'Oregon', 'OR', 'US'),
  ('altoona', 'altoona-johnstown', 'Pennsylvania', 'PA', 'US'),
  ('chambersburg', 'cumberland valley', 'Pennsylvania', 'PA', 'US'),
  ('erie', 'erie', 'Pennsylvania', 'PA', 'US'),
  ('harrisburg', 'harrisburg', 'Pennsylvania', 'PA', 'US'),
  ('lancaster', 'lancaster', 'Pennsylvania', 'PA', 'US'),
  ('allentown', 'lehigh valley', 'Pennsylvania', 'PA', 'US'),
  ('meadville', 'meadville', 'Pennsylvania', 'PA', 'US'),
  ('philadelphia', 'philadelphia', 'Pennsylvania', 'PA', 'US'),
  ('pittsburgh', 'pittsburgh', 'Pennsylvania', 'PA', 'US'),
  ('poconos', 'poconos', 'Pennsylvania', 'PA', 'US'),
  ('reading', 'reading', 'Pennsylvania', 'PA', 'US'),
  ('scranton', 'scranton / wilkes-barre', 'Pennsylvania', 'PA', 'US'),
  ('pennstate', 'state college', 'Pennsylvania', 'PA', 'US'),
  ('williamsport', 'williamsport', 'Pennsylvania', 'PA', 'US'),
  ('york', 'york', 'Pennsylvania', 'PA', 'US'),
  ('providence', 'rhode island', 'Rhode Island', 'RI', 'US'),
  ('charleston', 'charleston', 'South Carolina', 'SC', 'US'),
  ('columbia', 'columbia', 'South Carolina', 'SC', 'US'),
  ('florencesc', 'florence', 'South Carolina', 'SC', 'US'),
  ('greenville', 'greenville / upstate', 'South Carolina', 'SC', 'US'),
  ('hiltonhead', 'hilton head', 'South Carolina', 'SC', 'US'),
  ('myrtlebeach', 'myrtle beach', 'South Carolina', 'SC', 'US'),
  ('nesd', 'northeast SD', 'South Dakota', 'SD', 'US'),
  ('csd', 'pierre / central SD', 'South Dakota', 'SD', 'US'),
  ('rapidcity', 'rapid city / west SD', 'South Dakota', 'SD', 'US'),
  ('siouxfalls', 'sioux falls / SE SD', 'South Dakota', 'SD', 'US'),
  ('sd', 'south dakota', 'South Dakota', 'SD', 'US'),
  ('chattanooga', 'chattanooga', 'Tennessee', 'TN', 'US'),
  ('clarksville', 'clarksville', 'Tennessee', 'TN', 'US'),
  ('cookeville', 'cookeville', 'Tennessee', 'TN', 'US'),
  ('jacksontn', 'jackson', 'Tennessee', 'TN', 'US'),
  ('knoxville', 'knoxville', 'Tennessee', 'TN', 'US'),
  ('memphis', 'memphis', 'Tennessee', 'TN', 'US'),
  ('nashville', 'nashville', 'Tennessee', 'TN', 'US'),
  ('tricities', 'tri-cities', 'Tennessee', 'TN', 'US'),
  ('abilene', 'abilene', 'Texas', 'TX', 'US'),
  ('amarillo', 'amarillo', 'Texas', 'TX', 'US'),
  ('austin', 'austin', 'Texas', 'TX', 'US'),
  ('beaumont', 'beaumont / port arthur', 'Texas', 'TX', 'US'),
  ('brownsville', 'brownsville', 'Texas', 'TX', 'US'),
  ('collegestation', 'college station', 'Texas', 'TX', 'US'),
  ('corpuschristi', 'corpus christi', 'Texas', 'TX', 'US'),
  ('dallas', 'dallas / fort worth', 'Texas', 'TX', 'US'),
  ('nacogdoches', 'deep east texas', 'Texas', 'TX', 'US'),
  ('delrio', 'del rio / eagle pass', 'Texas', 'TX', 'US'),
  ('elpaso', 'el paso', 'Texas', 'TX', 'US'),
  ('galveston', 'galveston', 'Texas', 'TX', 'US'),
  ('houston', 'houston', 'Texas', 'TX', 'US'),
  ('killeen', 'killeen / temple / ft hood', 'Texas', 'TX', 'US'),
  ('laredo', 'laredo', 'Texas', 'TX', 'US'),
  ('lubbock', 'lubbock', 'Texas', 'TX', 'US'),
  ('mcallen', 'mcallen / edinburg', 'Texas', 'TX', 'US'),
  ('odessa', 'odessa / midland', 'Texas', 'TX', 'US'),
  ('sanangelo', 'san angelo', 'Texas', 'TX', 'US'),
  ('sanantonio', 'san antonio', 'Texas', 'TX', 'US'),
  ('sanmarcos', 'san marcos', 'Texas', 'TX', 'US'),
  ('bigbend', 'southwest TX', 'Texas', 'TX', 'US'),
  ('texoma', 'texoma', 'Texas', 'TX', 'US'),
  ('easttexas', 'tyler / east TX', 'Texas', 'TX', 'US'),
  ('victoriatx', 'victoria', 'Texas', 'TX', 'US'),
  ('waco', 'waco', 'Texas', 'TX', 'US'),
  ('wichitafalls', 'wichita falls', 'Texas', 'TX', 'US'),
  ('logan', 'logan', 'Utah', 'UT', 'US'),
  ('ogden', 'ogden-clearfield', 'Utah', 'UT', 'US'),
  ('provo', 'provo / orem', 'Utah', 'UT', 'US'),
  ('saltlakecity', 'salt lake city', 'Utah', 'UT', 'US'),
  ('stgeorge', 'st george', 'Utah', 'UT', 'US'),
  ('vermont', 'vermont', 'Vermont', 'VT', 'US'),
  ('charlottesville', 'charlottesville', 'Virginia', 'VA', 'US'),
  ('danville', 'danville', 'Virginia', 'VA', 'US'),
  ('fredericksburg', 'fredericksburg', 'Virginia', 'VA', 'US'),
  ('norfolk', 'hampton roads', 'Virginia', 'VA', 'US'),
  ('harrisonburg', 'harrisonburg', 'Virginia', 'VA', 'US'),
  ('lynchburg', 'lynchburg', 'Virginia', 'VA', 'US'),
  ('blacksburg', 'new river valley', 'Virginia', 'VA', 'US'),
  ('richmond', 'richmond', 'Virginia', 'VA', 'US'),
  ('roanoke', 'roanoke', 'Virginia', 'VA', 'US'),
  ('swva', 'southwest VA', 'Virginia', 'VA', 'US'),
  ('winchester', 'winchester', 'Virginia', 'VA', 'US'),
  ('bellingham', 'bellingham', 'Washington', 'WA', 'US'),
  ('kpr', 'kennewick-pasco-richland', 'Washington', 'WA', 'US'),
  ('moseslake', 'moses lake', 'Washington', 'WA', 'US'),
  ('olympic', 'olympic peninsula', 'Washington', 'WA', 'US'),
  ('pullman', 'pullman / moscow', 'Washington', 'WA', 'US'),
  ('seattle', 'seattle-tacoma', 'Washington', 'WA', 'US'),
  ('skagit', 'skagit / island / SJI', 'Washington', 'WA', 'US'),
  ('spokane', 'spokane / coeur d''alene', 'Washington', 'WA', 'US'),
  ('wenatchee', 'wenatchee', 'Washington', 'WA', 'US'),
  ('yakima', 'yakima', 'Washington', 'WA', 'US'),
  ('charlestonwv', 'charleston', 'West Virginia', 'WV', 'US'),
  ('martinsburg', 'eastern panhandle', 'West Virginia', 'WV', 'US'),
  ('huntington', 'huntington-ashland', 'West Virginia', 'WV', 'US'),
  ('morgantown', 'morgantown', 'West Virginia', 'WV', 'US'),
  ('wheeling', 'northern panhandle', 'West Virginia', 'WV', 'US'),
  ('parkersburg', 'parkersburg-marietta', 'West Virginia', 'WV', 'US'),
  ('swv', 'southern WV', 'West Virginia', 'WV', 'US'),
  ('wv', 'west virginia (old)', 'West Virginia', 'WV', 'US'),
  ('appleton', 'appleton-oshkosh-FDL', 'Wisconsin', 'WI', 'US'),
  ('eauclaire', 'eau claire', 'Wisconsin', 'WI', 'US'),
  ('greenbay', 'green bay', 'Wisconsin', 'WI', 'US'),
  ('janesville', 'janesville', 'Wisconsin', 'WI', 'US'),
  ('racine', 'kenosha-racine', 'Wisconsin', 'WI', 'US'),
  ('lacrosse', 'la crosse', 'Wisconsin', 'WI', 'US'),
  ('madison', 'madison', 'Wisconsin', 'WI', 'US'),
  ('milwaukee', 'milwaukee', 'Wisconsin', 'WI', 'US'),
  ('northernwi', 'northern WI', 'Wisconsin', 'WI', 'US'),
  ('sheboygan', 'sheboygan', 'Wisconsin', 'WI', 'US'),
  ('wausau', 'wausau', 'Wisconsin', 'WI', 'US'),
  ('wyoming', 'wyoming', 'Wyoming', 'WY', 'US'),
  ('micronesia', 'guam-micronesia', 'Territories', NULL, 'US'),
  ('puertorico', 'puerto rico', 'Territories', NULL, 'US'),
  ('virgin', 'U.S. virgin islands', 'Territories', NULL, 'US'),
  ('acapulco', 'acapulco', NULL, NULL, 'MX'),
  ('bajasur', 'baja california sur', NULL, NULL, 'MX'),
  ('chihuahua', 'chihuahua', NULL, NULL, 'MX'),
  ('juarez', 'ciudad juarez', NULL, NULL, 'MX'),
  ('guadalajara', 'guadalajara', NULL, NULL, 'MX'),
  ('guanajuato', 'guanajuato', NULL, NULL, 'MX'),
  ('hermosillo', 'hermosillo', NULL, NULL, 'MX'),
  ('mazatlan', 'mazatlan', NULL, NULL, 'MX'),
  ('mexicocity', 'mexico city', NULL, NULL, 'MX'),
  ('monterrey', 'monterrey', NULL, NULL, 'MX'),
  ('oaxaca', 'oaxaca', NULL, NULL, 'MX'),
  ('puebla', 'puebla', NULL, NULL, 'MX'),
  ('pv', 'puerto vallarta', NULL, NULL, 'MX'),
  ('tijuana', 'tijuana', NULL, NULL, 'MX'),
  ('veracruz', 'veracruz', NULL, NULL, 'MX'),
  ('yucatan', 'yucatan', NULL, NULL, 'MX')
ON CONFLICT (slug) DO NOTHING;

