apiVersion: v1
kind: Service
metadata:
  name: fraud
  labels:
    app.kubernetes.io/name: fraud
    app.kubernetes.io/component: rust-engine
    app.kubernetes.io/part-of: nomarkup
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fraud
  ports:
    - name: grpc
      port: 50056
      targetPort: grpc
      protocol: TCP
