apiVersion: v1
kind: Service
metadata:
  name: trust
  labels:
    app.kubernetes.io/name: trust
    app.kubernetes.io/component: rust-engine
    app.kubernetes.io/part-of: nomarkup
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: trust
  ports:
    - name: grpc
      port: 50057
      targetPort: grpc
      protocol: TCP
