apiVersion: v1
kind: Service
metadata:
  name: chat
  labels:
    app.kubernetes.io/name: chat
    app.kubernetes.io/component: go-service
    app.kubernetes.io/part-of: nomarkup
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chat
  ports:
    - name: grpc
      port: 50055
      targetPort: grpc
      protocol: TCP
    - name: ws
      port: 50065
      targetPort: ws
      protocol: TCP
